---
# task/main file for deploy_haproxy
- name: "Import prerequisites.yml"
  ansible.builtin.include_tasks: prerequisites.yml

- name: "Import install_host.yml"
  ansible.builtin.include_tasks: install_host.yml
  when: deploy_haproxy_deploy_method == 'host'

- name: "Import configure.yml"
  ansible.builtin.include_tasks: configure.yml

- name: "Import install_docker.yml"
  ansible.builtin.include_tasks: "install_docker.yml"
  when: deploy_haproxy_deploy_method == 'docker'

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers
